



let books = [
{ author: 'Abbott, Edwin', title: 'Flatland: A Romance of Many Dimensions', genre: 'Fiction', finished: 'May 2016', rating: 5, recommended: null},
{ author: 'Abercrombie, Joe', title: 'The Blade Itself (The First Law #1)', genre: 'Fantasy', finished: 'Jul 2018', rating: 4},
{ author: 'Abercrombie, Joe', title: 'Before They Are Hanged (The First Law #2)', genre: 'Fantasy', finished: 'Jul 2018', rating: 5, recommended: null},
{ author: 'Abercrombie, Joe', title: 'Last Argument of Kings (The First Law #3)', genre: 'Fantasy', finished: 'Aug 2018', rating: 5, recommended: null},
{ author: 'Adams, Douglas',	title: 'Dirk Gently\'s Holistic Detective Agency (Dirk Gently #1)', genre: 'Science Fiction', finished: null, rating: null, recommended: null},
{ author: 'Adams, Douglas',	title: 'A Hitchhiker\'s Guide to the Galaxy (#1)', genre: 'Science Fiction', finished: 'May 2017', rating: 3, recommended: null},
{ author: 'Adams, Douglas',	title: 'Life, the Universe and Everything (#3)', genre: 'Science Fiction', finished: 'Jun 2017', rating: -1, recommended: null},
{ author: 'Adams, Douglas',	title: 'The Restaurant at the End of the Universe (#2)', genre: 'Science Fiction', finished:'May 2017', rating: 2, recommended: null},
{ author: 'Adams, Richard',	title: 'The Plague Dogs', genre: 'Animal Fiction', finished: null, rating: null, recommended: null},
{ author: 'Adams, Richard',	title: 'Watership Down', genre: 'Animal Fiction', finished:	'Oct 2014', rating: 4, recommended: null},
{ author: 'Adams, Richard',	title: 'Daniel', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Adams, Richard',	title: 'Maia (Beklan Empire #2)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Adams, Richard',	title: 'Shardik (Beklan Empire #1)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Adams, Richard',	title: 'The Girl in a Swing', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Adams, Richard',	title: 'Traveller', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Adler, Renata', title: 'Speedboat', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Albaret, Celeste', title: 'Monsieur Proust', genre: 'Biography', finished: null, rating: null, recommended: null},
{ author: 'Albom, Mitch', title: 'The Five People You Meet in Heaven', genre: 'Fiction', finished: null, rating: null, recommended: null}, 
{ author: 'Albom, Mitch', title: 'Tuesdays with Morrie', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'A Garland for Girls', genre: 'Fiction',	finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'A Long Fatal Love Chase', genre: 'Fiction',	finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'A Modern Mephistopheles', genre: 'Fiction',	finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'A Whisper in the Dark', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'Behind a Mask, or, a Woman\'s Power', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'Eight Cousins (Eight Cousins #1)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'Good Wives', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'Hospital Sketches', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'Jack and Jill', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'Jo\'s Boys', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'Little Men', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'Little Women', genre: 'Fiction', finished: null, rating: 5, recommended: null},
{ author: 'Alcott, Louisa May', title: 'Moods', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'Rose in Bloom (Eight Cousins #2)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'The Inheritance', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'The Mysterious Key and what it Opened', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'Under the Lilacs', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alcott, Louisa May', title: 'Work: A Story of Experience', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alexander, Robert', title: 'Rasputin\'s Daughter', genre: 'Historical Fiction', finished: 'Oct 2017', rating: 1, recommended: null},
{ author: 'Alexander, Robert', title: 'The Kitchen Boy: A Novel of the Last Tsar', genre: 'Historical Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alexander, Tasha', title: 'And Only to Deceive',	genre: 'Historical Fiction', finished: null, rating: null, recommended: null},
{ author: 'Ali, Monica', title: 'Brick Lane', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alighieri, Dante', title: 'Inferno', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Alighieri, Dante', title: 'The Divine Comedy', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Allen, Brooke', title: 'Moral Minority: Our Skeptical Founding Fathers', genre: 'History', finished: null, rating: null, recommended: null},
{ author: 'Allende, Isabel', title: 'Daughter of Fortune', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Allende, Isabel', title: 'Eva Luna', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Allende, Isabel', title: 'Paula', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Allende, Isabel', title: 'The House of the Spirits', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Allison, Fitzsimons', title: 'The Cruelty of Heresy', genre: 'Religion', finished: null, rating: null, recommended: null},
{ author: 'Ammaniti, Niccolo', title: 'I\'m Not Scared', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Amos, Tori', title: 'Piece by Piece', genre: 'Autobiography', finished: null, rating: null, recommended: null},
{ author: 'Anderson, John D, Jr.', title: 'Fundamentals of Aerodynamics', genre: 'Flying', finished: null, rating: null, recommended: null},
{ author: 'Anderson, Kevin J.', title: 'A Forest of Stars (The Saga of Seven Suns #2)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Anderson, Kevin J.', title: 'Hidden Empire (The Saga of Seven Suns #1)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Anderson, Kevin J.', title: 'Horizon Storms (The Saga of Seven Suns #3)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Anderson, Kevin J.', title: 'Metal Swarm (The Saga of Seven Suns #6)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Anderson, Kevin J.', title: 'Of Fire and Night (The Saga of Seven Suns #5)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Anderson, Kevin J.', title: 'Scattered Suns (The Saga of Seven Suns #4)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Anderson, Kevin J.', title: 'The Ashes of Worlds (The Saga of Seven Suns #7)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Anderson, Matthew Tobin', title:'Feed', genre:'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Anderson, Melissa', title: 'The Way I See It: A Look Back at My Life on Little House', genre: 'Autobiography', finished: null, rating: null, recommended: null},
{ author: 'Andrews, C.', title: 'Less is More: Embracing Simplicty', genre: 'Self Improvement', finished: null, rating: null, recommended: null},
{ author: 'Apollonius of Rhodes', title: 'The Voyage of Argo: The Argonautica', genre: 'Poetry', finished: null, rating: null, recommended: null},
{ author: 'Appelbaum, Steven', title: 'ABC: Practical Guide to Dog Training', genre: 'Dog Training', finished: null, rating: 3, recommended: null},
{ author: 'Appleman-Jurman, Alicia', title: 'Alicia: My Story', genre: 'Memoir', finished: null, rating: null, recommended: null},
{ author: 'Apuleius, Lucius', title: 'The Golden Ass', genre: 'Mythology', finished: null, rating: null, recommended: null},
{ author: 'Arden, Katherine', title: 'The Bear and the Nightingale (Winternight Trilogy #1)', genre: 'Fantasy', finished: null, rating: null, recommended: null},
{ author: 'Aristotle', title: 'The Nicomachean Ethics', genre: 'Philosophy', finished: null, rating: null, recommended: null},
{ author: 'Arngrim, Alison', title: 'Confessions of a Prairie Bitch: How I Survived Nellie Olsen', genre: 'Memoir', finished: null, rating: null, recommended: null},
{ author: 'Aronsfeld, Caeser C.', title: 'Text of the Holocaust', genre: 'History', finished: null, rating: null, recommended: null},
{ author: 'Asia, Reza', title: 'Zealot', genre: 'Religion', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'Fantastic Voyage', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'Forward the Foundation (Foundation: Prequel #2)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'Foundation (Foundation #1)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'Foundation and Earth (Foundation #5)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'Foundation and Empire (Foundation #2)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'Foundation\'s Edge (Foundation #4)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'Nightfall', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'Prelude to Foundation (Foundation: Prequel #1)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'Robots and Empire (Robot #4)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'Second Foundation (Foundation #3)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'The Caves of Steel (Robot #1)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'The End of Eternity', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'The Gods Themselves', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'The Last Question', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'The Naked Sun (Robot #2)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'The Robots of Dawn (Robot #3)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Asimov, Isaac', title: 'Asimov\'s Guide to the Bible	Religion', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Astaire, Fred', title: 'Steps in Time', genre: 'Autobiography', finished: null, rating: null, recommended: null},
{ author: 'Atwood, Margaret', title: 'Alias Grace', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Atwood, Margaret', title: 'Cat\'s Eye', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Atwood, Margaret', title: 'MaddAddam (MaddAddam #3)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Atwood, Margaret', title: 'Oryx and Crake (MaddAddam #1)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Atwood, Margaret', title: 'The Blind Assassin', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Atwood, Margaret', title: 'The Edible Woman', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Atwood, Margaret', title: 'The Handmaid\'s Tale', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Atwood, Margaret', title: 'The Penelopiad', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Atwood, Margaret', title: 'The Robber Bride', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Atwood, Margaret', title: 'The Year of the Flood (MaddAddam #2)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Augustine of Hippo', title: 'Confessions', genre: 'Literature', finished: null, rating: null, recommended: null},
{ author: 'Austen, Jane', title: 'Lady Susan', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Austen, Jane', title: 'Mansfield Park', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Austen, Jane', title: 'Emma', genre: 'Romance', finished: 'Nov 2014', rating: 4, recommended: null},
{ author: 'Austen, Jane', title: 'Northanger Abbey', genre: 'Romance', finished: 'Nov 2017', rating: 4, recommended: null},
{ author: 'Austen, Jane', title: 'Persuasion', genre: 'Romance', finished: 'Oct 2015', rating: 3, recommended: null},
{ author: 'Austen, Jane', title: 'Pride and Prejudice', genre: 'Romance', finished: null, rating: 5, recommended: null},
{ author: 'Austen, Jane', title: 'Sense and Sensibility', genre: 'Romance', finished: 'Jul 2016', rating: 4, recommended: null},
{ author: 'Auster, Paul', title: 'Man in the Dark', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Auster, Paul', title: 'Oracle Night', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Austin, Emily R.', title: 'Oh Honey', genre: 'Fiction', finished: null, rating: null, recommended: null}, 
{ author: 'Avi', title: 'A Beginning, a Muddle, and an End', genre: 'Animal Fiction', finished:	'Nov 2015', rating:	5, recommended: null},
{ author: 'Avi', title: 'Poppy (#1)', genre: 'Animal Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Poppy and Ereth (#5)', genre: 'Animal Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Poppy and Rye (#2)', genre: 'Animal Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Poppy\'s Return (#4)', genre: 'Animal Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Ragweed (#0)', genre: 'Animal Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'The End of the Beginning', genre: 'Animal Fiction', finished: null, rating: 5, recommended: null},
{ author: 'Avi', title: 'The Good Dog', genre: 'Animal Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'What do Fish have to do with Anything?', genre: 'Animal Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Blue Heron', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Crispin: At the Edge of the World', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Crispin: The Cross of Lead', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Crispin: The End of Time', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Devil\'s Race', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Ereth\'s Birthday (#3)', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Midnight Magic', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Murder at Midnight ', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Nothing But the Truth', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'Romeo and Juliet - Together (and Alive!) at Last', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'The Man Who was Poe', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'The Secret School', genre: 'Fiction', finished: null, rating: null, recommended: null},
{ author: 'Avi', title: 'The Seer of Shadows', genre: 'Fiction', finished: null, rating: null, recommended: null},
];

export default books;